// <auto-generated>
// This file was generated by SceneEnumGenerator.
// </auto-generated>

public enum SceneEnum
{
    Env_Stage,
    Env_Map,
    Pri_Stage1,
    SampleScene,
    Test_Stage,
    Test_StageSelect,
    Test_Ui_InGame,
}
