// <auto-generated>
// This file was generated by SceneEnumGenerator.
// </auto-generated>

public enum SceneEnum
{
    Env_Stage,
    Map,
    Pri_Stage1,
    Stage1,
    Stage2,
    Stage3,
    Test_3dStage,
    Test_Game,
    Test_Player,
    Test_PlayerController,
    Test_Stage,
    Test_StageSelect,
    Test_Ui_InGame,
    Fadescene,
    Test,
    NewScene,
}
