using System.IO;
using System.Linq;
using System.Text;
using Module.EditorExtension.Runtime;
using UnityEditor;
using UnityEngine;

namespace Module.EditorExtension.Editor
{
    public class SceneEnumGeneratorWindow : EditorWindow
    {
        private SceneEnumGeneratorSettings _settings;

        [MenuItem("Tools/Scene Enum Generator")]
        public static void ShowWindow()
        {
            GetWindow<SceneEnumGeneratorWindow>("Scene Enum Generator");
        }

        private void OnGUI()
        {
            GUILayout.Label("Scene Enum Generator", EditorStyles.boldLabel);

            _settings = (SceneEnumGeneratorSettings)EditorGUILayout.ObjectField(
                "Settings Asset", _settings, typeof(SceneEnumGeneratorSettings), false);

            if (_settings != null)
            {
                // Display settings in a disabled state
                EditorGUI.BeginDisabledGroup(true);
                EditorGUILayout.TextField("Search Directory", _settings.searchDirectory);
                EditorGUILayout.TextField("Output Directory", _settings.outputDirectory);
                EditorGUILayout.TextField("Enum Name", _settings.enumName);
                EditorGUILayout.TextField("File Name", _settings.fileName);
                EditorGUI.EndDisabledGroup();

                if (GUILayout.Button("Generate Enum"))
                {
                    GenerateEnum();
                }
            }
            else
            {
                EditorGUILayout.HelpBox("Please create and assign a Settings Asset.", MessageType.Info);
                if (GUILayout.Button("Create New Settings Asset"))
                {
                    CreateSettingsAsset();
                }
            }
        }

        private void GenerateEnum()
        {
            if (_settings == null)
            {
                Debug.LogError("Settings asset not assigned.");
                return;
            }

            if (!Directory.Exists(_settings.searchDirectory))
            {
                Debug.LogError($"Search directory not found: {_settings.searchDirectory}");
                return;
            }

            if (!Directory.Exists(_settings.outputDirectory))
            {
                Debug.Log($"Output directory not found. Creating directory: {_settings.outputDirectory}");
                Directory.CreateDirectory(_settings.outputDirectory);
            }

            var sceneGuids = AssetDatabase.FindAssets("t:Scene", new[] { _settings.searchDirectory });
            var scenePaths = sceneGuids.Select(AssetDatabase.GUIDToAssetPath).ToList();

            if (scenePaths.Count == 0)
            {
                Debug.LogWarning($"No scenes found in directory: {_settings.searchDirectory}");
                return;
            }

            var stringBuilder = new StringBuilder();
            stringBuilder.AppendLine("// <auto-generated>");
            stringBuilder.AppendLine("// This file was generated by SceneEnumGenerator.");
            stringBuilder.AppendLine("// </auto-generated>");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine($"public enum {_settings.enumName}");
            stringBuilder.AppendLine("{");

            foreach (var scenePath in scenePaths)
            {
                var sceneName = Path.GetFileNameWithoutExtension(scenePath);
                var sanitizedName = new string(sceneName.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());
                if (string.IsNullOrEmpty(sanitizedName) || !char.IsLetter(sanitizedName[0]))
                {
                    sanitizedName = "_" + sanitizedName;
                }
                stringBuilder.AppendLine($"    {sanitizedName},");
            }

            stringBuilder.AppendLine("}");

            var outputPath = Path.Combine(_settings.outputDirectory, _settings.fileName);
            try
            {
                File.WriteAllText(outputPath, stringBuilder.ToString());
                AssetDatabase.Refresh();
                Debug.Log($"Successfully generated enum {_settings.enumName} at {outputPath}");
            }
            catch (System.Exception e)
            {
                Debug.LogError($"Failed to write enum file: {e.Message}");
            }
        }

        private void CreateSettingsAsset()
        {
            string path = EditorUtility.SaveFilePanelInProject(
                "Save Settings Asset",
                "SceneEnumGeneratorSettings",
                "asset",
                "Please enter a file name to save the settings to.");

            if (string.IsNullOrEmpty(path)) return;

            var asset = ScriptableObject.CreateInstance<SceneEnumGeneratorSettings>();
            AssetDatabase.CreateAsset(asset, path);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            _settings = asset;
        }
    }
}
